Edit .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -31,18 +31,19 @@ build:
     - cd applications && ls -la
     - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
   script:
-    - for SERVICE in $SERVICES; do
-        echo "Building and tagging Docker image for $SERVICE...";
-        cd applications && ls -la
-        cd $SERVICE || { echo "$SERVICE directory not found!"; exit 1; }
-        go mod tidy
-        go mod vendor
-        docker build -t backend_$SERVICE:latest .
-        docker tag backend_$SERVICE:latest $DOCKER_IMAGE_PREFIX-$SERVICE:latest
-        docker push $DOCKER_IMAGE_PREFIX-$SERVICE:latest
-        cd ..
-      done
-    - echo "Build, tag, and push completed for all services."
+  - |
+    for SERVICE in $SERVICES; do
+      echo "Building and tagging Docker image for $SERVICE..."
+      cd applications || { echo "applications directory not found!"; exit 1; }
+      cd $SERVICE || { echo "$SERVICE directory not found!"; exit 1; }
+      go mod tidy
+      go mod vendor
+      docker build -t backend_$SERVICE:latest .
+      docker tag backend_$SERVICE:latest $DOCKER_IMAGE_PREFIX-$SERVICE:latest
+      docker push $DOCKER_IMAGE_PREFIX-$SERVICE:latest
+      cd ../..
+    done
+  - echo "Build, tag, and push completed for all services."
 
 deploy_microservices:
   stage: deploy
