Edit .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -14,26 +14,26 @@ build:
     - apk add --no-cache docker-cli
     - export DOCKER_HOST="unix:///var/run/docker.sock"
   
-  script:
-    - echo "SERVICES: $SERVICES"  # Debugging line
-    - SERVICES=$(echo $SERVICES | tr -s ' ' '\n')  # Remove any extra spaces/newlines
-    - echo "Starting the loop..."
-    - for SERVICE in $SERVICES; do
-    - echo "Processing service: $SERVICE"  # Debugging line
-    - SERVICE_PATH="applications/$SERVICE"
-    - echo "Service path: $SERVICE_PATH"  # Debugging line
-    - if [ -d "$SERVICE_PATH" ]; then
-    - echo "Listing contents of $SERVICE_PATH directory:"
-    - ls -l $SERVICE_PATH || exit 1  # Ensure the service directory exists
-    - cd $SERVICE_PATH || exit 1  # Change into the service directory
-    - docker build -t $DOCKER_IMAGE_PREFIX-$SERVICE:latest .
-    - docker push $DOCKER_IMAGE_PREFIX-$SERVICE:latest
-    - cd - > /dev/null  # Return to previous directory silently
-    - else
-    - echo "$SERVICE_PATH directory does not exist!"  # Handle the missing directory
-    - exit 1
-    - fi
-    - done
+  # script:
+  #   - echo "SERVICES: $SERVICES"  # Debugging line
+  #   - SERVICES=$(echo $SERVICES | tr -s ' ' '\n')  # Remove any extra spaces/newlines
+  #   - echo "Starting the loop..."
+  #   - for SERVICE in $SERVICES; do
+  #   - echo "Processing service: $SERVICE"  # Debugging line
+  #   - SERVICE_PATH="applications/$SERVICE"
+  #   - echo "Service path: $SERVICE_PATH"  # Debugging line
+  #   - if [ -d "$SERVICE_PATH" ]; then
+  #   - echo "Listing contents of $SERVICE_PATH directory:"
+  #   - ls -l $SERVICE_PATH || exit 1  # Ensure the service directory exists
+  #   - cd $SERVICE_PATH || exit 1  # Change into the service directory
+  #   - docker build -t $DOCKER_IMAGE_PREFIX-$SERVICE:latest .
+  #   - docker push $DOCKER_IMAGE_PREFIX-$SERVICE:latest
+  #   - cd - > /dev/null  # Return to previous directory silently
+  #   - else
+  #   - echo "$SERVICE_PATH directory does not exist!"  # Handle the missing directory
+  #   - exit 1
+  #   - fi
+  #   - done
 
 deploy_microservices:
   stage: deploy
