Edit .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -8,37 +8,37 @@ stages:
 variables:
   DOCKER_IMAGE_PREFIX: nagagogulan/aimx
   SERVICES: "identity forms roles dataset profile user_management"
-  GIT_REPO_URL: "https://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@github.com/PecozQ/aimx-library.git"
+  GIT_REPO_URL: " git clone git@github.com:PecozQ/aimx-library.git"  # or use git@github.com:... if using SSH
   GIT_BRANCH: "dev"
 
 clone:
   stage: clone
   script:
     - apk update && apk add git
-    - git clone --branch $GIT_BRANCH $GIT_REPO_URL source
-    - ls -alh # List the contents of the current directory to check if 'source' exists
-    - cd source
-    - git config --global url."git@github.com:".insteadof "https://github.com/"  # Ensure SSH is used for GitHub
+    - echo "Cloning repo..."
+    - git clone --branch $GIT_BRANCH $GIT_REPO_URL source || { echo "Git clone failed"; exit 1; }
+    - ls -alh source
+    - cd source || { echo "'source' directory missing"; exit 1; }
     - go env -w GOPRIVATE=github.com/PecozQ/*
     - go env -w GO111MODULE=on
-    - ls -alh # List contents of 'source' to check if files are there
 
 build:
   stage: build
+  services:
+    - docker:dind
   before_script:
     - apk update && apk add docker
-    - cd source  # Change to the correct directory
+    - cd source
     - export GOPRIVATE=github.com/PecozQ/*
     - export GO111MODULE=on
     - export DOCKER_HOST="unix:///var/run/docker.sock"
-    - ls -alh # List contents of 'source' before proceeding with build
   script:
     - go mod tidy
     - go mod vendor
     - |
       for SERVICE in $SERVICES; do
         echo "Building $SERVICE..."
-        cd applications/$SERVICE || exit 1
+        cd applications/$SERVICE || { echo "Service '$SERVICE' not found"; exit 1; }
         go mod tidy
         go mod vendor
         docker build -t $DOCKER_IMAGE_PREFIX-$SERVICE:latest .
@@ -60,37 +60,22 @@ deploy_microservices:
   script:
     - |
       ssh $EC2_USER@$EC2_HOST "
-        echo 'Logging into Docker...'
         docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
 
         for SERVICE in $SERVICES; do
-          echo \"Pulling \$SERVICE image...\"
+          echo \"Deploying \$SERVICE...\"
           docker pull $DOCKER_IMAGE_PREFIX-\$SERVICE:latest
 
-          echo \"Stopping and removing existing container for \$SERVICE...\"
           docker ps -q --filter name=\$SERVICE | xargs -r docker stop
           docker ps -aq --filter name=\$SERVICE | xargs -r docker rm
 
-          echo \"Starting new container for \$SERVICE...\"
           case \$SERVICE in
-            identity)
-              docker run -d --name identity -p 8081:8081 $DOCKER_IMAGE_PREFIX-identity:latest
-              ;;
-            forms)
-              docker run -d --name forms -p 8082:8082 $DOCKER_IMAGE_PREFIX-forms:latest
-              ;;
-            roles)
-              docker run -d --name roles -p 8083:8083 $DOCKER_IMAGE_PREFIX-roles:latest
-              ;;
-            dataset)
-              docker run -d --name dataset -p 8084:8084 $DOCKER_IMAGE_PREFIX-dataset:latest
-              ;;
-            profile)
-              docker run -d --name profile -p 8085:8085 $DOCKER_IMAGE_PREFIX-profile:latest
-              ;;
-            user_management)
-              docker run -d --name user_management -p 8086:8086 $DOCKER_IMAGE_PREFIX-user_management:latest
-              ;;
+            identity) docker run -d --name identity -p 8081:8081 $DOCKER_IMAGE_PREFIX-identity:latest ;;
+            forms) docker run -d --name forms -p 8082:8082 $DOCKER_IMAGE_PREFIX-forms:latest ;;
+            roles) docker run -d --name roles -p 8083:8083 $DOCKER_IMAGE_PREFIX-roles:latest ;;
+            dataset) docker run -d --name dataset -p 8084:8084 $DOCKER_IMAGE_PREFIX-dataset:latest ;;
+            profile) docker run -d --name profile -p 8085:8085 $DOCKER_IMAGE_PREFIX-profile:latest ;;
+            user_management) docker run -d --name user_management -p 8086:8086 $DOCKER_IMAGE_PREFIX-user_management:latest ;;
           esac
         done
       "
