Edit .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -26,20 +26,18 @@ build:
     DOCKER_TLS_CERTDIR: ""
   before_script:
     - apk update && apk add git go
-  script:
     - cd source
-    - echo "Verifying structure..."
-    - ls -la
-    - echo "Navigating to dataset service..."
-    - cd applications/dataset || { echo "Service 'dataset' not found"; exit 1; }
-
-    - echo "Running go mod tidy..."
+  script:
+    - echo "Running go mod tidy and vendor for dataset service..."
+    - cd applications/dataset || { echo "Dataset service not found"; exit 1; }
     - go mod tidy
-    - echo "Running go mod vendor..."
     - go mod vendor
 
-    - echo "Building Docker image..."
-    - docker build -t $DOCKER_IMAGE_PREFIX-dataset:latest .
+    echo "Building Docker image for dataset..."
+    docker build -t $DOCKER_IMAGE_PREFIX-dataset:latest .
 
-    - echo "Pushing Docker image to Docker Hub..."
-    - docker push $DOCKER_IMAGE_PREFIX-dataset:latest
+    echo "Pushing Docker image for dataset..."
+    docker push $DOCKER_IMAGE_PREFIX-dataset:latest
+
+    cd - > /dev/null
+
