Edit .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -17,26 +17,24 @@ build:
     - export DOCKER_HOST="unix:///var/run/docker.sock"
   
   script:
-  - echo "SERVICES: $SERVICES"  # Debugging line
-  - SERVICES=$(echo $SERVICES | tr -s ' ' '\n')  # Remove any extra spaces/newlines
-  - for SERVICE in $SERVICES; do
-      echo "Processing service: $SERVICE"  # Debugging line
-      SERVICE_PATH="applications/$SERVICE"
-      echo "Service path: $SERVICE_PATH"  # Debugging line
-      if [ -d "$SERVICE_PATH" ]; then
-        echo "Listing contents of $SERVICE_PATH directory:"
-        ls -l $SERVICE_PATH || exit 1  # Ensure the service directory exists
-        cd $SERVICE_PATH || exit 1  # Change into the service directory
-        docker build -t $DOCKER_IMAGE_PREFIX-$SERVICE:latest .
-        docker push $DOCKER_IMAGE_PREFIX-$SERVICE:latest
-        cd - > /dev/null  # Return to previous directory silently
-      else
-        echo "$SERVICE_PATH directory does not exist!"  # Handle the missing directory
-        exit 1
-      fi
-    done
-
-
+    - echo "SERVICES: $SERVICES"  # Debugging line
+    - SERVICES=$(echo $SERVICES | tr -s ' ' '\n')  # Remove any extra spaces/newlines
+    - for SERVICE in $SERVICES; do
+        echo "Processing service: $SERVICE"  # Debugging line
+        SERVICE_PATH="applications/$SERVICE"
+        echo "Service path: $SERVICE_PATH"  # Debugging line
+        if [ -d "$SERVICE_PATH" ]; then
+          echo "Listing contents of $SERVICE_PATH directory:"
+          ls -l $SERVICE_PATH || exit 1  # Ensure the service directory exists
+          cd $SERVICE_PATH || exit 1  # Change into the service directory
+          docker build -t $DOCKER_IMAGE_PREFIX-$SERVICE:latest .
+          docker push $DOCKER_IMAGE_PREFIX-$SERVICE:latest
+          cd - > /dev/null  # Return to previous directory silently
+        else
+          echo "$SERVICE_PATH directory does not exist!"  # Handle the missing directory
+          exit 1
+        fi
+      done
 
 deploy_microservices:
   stage: deploy
@@ -49,20 +47,18 @@ deploy_microservices:
     - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
     - chmod 600 ~/.ssh/id_rsa
     - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
+  
   script:
     - |
       ssh $EC2_USER@$EC2_HOST "
         echo 'Logging into Docker...'
         docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
-
         for SERVICE in $SERVICES; do
           echo \"Pulling \$SERVICE image...\"
           docker pull $DOCKER_IMAGE_PREFIX-\$SERVICE:latest
-
           echo \"Stopping and removing existing container for \$SERVICE...\"
           docker ps -q --filter name=\$SERVICE | xargs -r docker stop
           docker ps -aq --filter name=\$SERVICE | xargs -r docker rm
-
           echo \"Starting new container for \$SERVICE...\"
           case \$SERVICE in
             identity)
